---
version: '3.6'
services:

  php:
    image: php:7.2-fpm-alpine3.10
    volumes:
    - ./frontend:/frontend
  
  web:
    image: nginx:1-alpine
    ports:
    - "8080:80"
    links:
    - php
    volumes:
    - ./frontend:/frontend
    - ./nginx.conf:/etc/nginx/conf.d/default.conf